#!/bin/bash
salir=0
opcion=0
#echo -e " Estamos en la carpeta: `pwd` \n"
ruta=Música
cd "$ruta"
while [ "$salir" == 0 ];do 
        existe=$(dpkg --get-selections | grep -w mpg123 | grep -w install)
        if [ "$existe" = " " ];then 
        `sudo apt-get install mpg123`
        fi
        case "$opcion" in
                0) #imprime menu
                   echo -e "\t\t\e[1;33m \n\n\n\t\t    B I E N V E N I D O   A:\n"       
                        echo -e "\t\t\e[1;37m  *********************______**************************** ""\e[0m"
                        echo -e "\t\t\e[1;37m  ***______***********|   _  \*************************** ""\e[0m"
                        echo -e "\t\t\e[1;37m  ***|   _ \**********|  |_| |**__*****__*____**______*** ""\e[0m"
                        echo -e "\t\t\e[1;37m  ***|  |_||**********|      /*|  \***/  |    \*|__  |*** ""\e[0m"
                        echo -e "\t\t\e[1;37m  ***|  ___/____*____*|     /**|   \*/   | --  \**/ /**** ""\e[0m"
                        echo -e "\t\t\e[1;37m  ***|  |***| __/ __ \|     \**|      /| |  ___/*/_ \**** ""\e[0m"
                        echo -e "\t\t\e[1;37m  ***|  |***| ||  ____|   _  \*|  |\ /*| |  |******\ \*** ""\e[0m"
                        echo -e "\t\t\e[1;37m  ***|  |***| ||  \___|  |_| /*|  |****| |  |***___/ /*** ""\e[0m"
                        echo -e "\t\t\e[1;37m  ***|__|***\_|*\_____|_____/**|__|****|_|__|***|___/**** ""\e[0m"
                        echo -e "\t\t\e[1;37m ***********************************************     **** ""\e[0m"
                   echo -e  "\t********REPRODUCTOR MP3********"
                   echo -e " Estamos en la carpeta: `pwd` \n"
                   echo -e  "\t1)REPRODUCIR UNA CANCION"
                   echo -e  "\t2)REPRODUCIR TODAS LAS CANCIONES"
                   echo -e  "\t3)LISTAR OPCIONES DEL REPRODUCTOR"
                   echo -e  "\t4)AYUDA"
                   echo -e  "\t5)SALIR"
                   read opcion;;
                1) echo uno
                echo "Dame la cancion que te gustaria escuchar:"
                read cancion

                `mpg123 $cancion`
                opcion=0 ;;
                2) echo dos
                `mpg123 *mp3`
                opcion=0 ;;
                3)echo "Tus canciones son: " 
                echo `ls | grep "mp3"`
                opcion=0 ;;             
                4) opcion=0
                echo -e "\e[1;33m\n\n\t\t**** INSTRUCCIONES ****\n\n"
                echo -e "\e[1;32m     Este es un reproductor de mp3\n"
                echo -e "Hay 5 opciones a elegir:\n\t 1)Reproduce una cancion del directorio Musica ;se debe especificar el nombre con la exte$
                echo -e "\n\t 2) Reproduce todas las canciones del directorio Musica"
                echo -e "\n\t 3) Lista las canciones del directorio Musica"
                echo -e "\n\t 4) Muestra este instructivo"
                echo -e "\n\t 5) Sale "
                echo -e "\e[1;31m\n\t\tPresiona 'enter' para volver al menú principal." "\e[0m"
                read
                ;;
                5) echo "***** ADIOOOS!! *****"
                echo -e "Presione una tecla para continuar..."
                  read
                  clear
                salir=1;;
                *) echo -e "\E[1;31m    Opcion inválida. Intente de nuevo"
                  echo -e "Presione una tecla para continuar..."
                  read
                  clear
        esac
done
